// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mockwritelock

import (
	"sync"

	"github.com/dcbickfo/redcache/internal/writelock"
)

// Ensure that MockLogger does implement writelock.Logger.
// If this is not the case, regenerate this file with mockery.
var _ writelock.Logger = &MockLogger{}

// MockLogger is a mock implementation of writelock.Logger.
//
//	func TestSomethingThatUsesLogger(t *testing.T) {
//
//		// make and configure a mocked writelock.Logger
//		mockedLogger := &MockLogger{
//			DebugFunc: func(msg string, args ...any)  {
//				panic("mock out the Debug method")
//			},
//			ErrorFunc: func(msg string, args ...any)  {
//				panic("mock out the Error method")
//			},
//		}
//
//		// use mockedLogger in code that requires writelock.Logger
//		// and then make assertions.
//
//	}
type MockLogger struct {
	// DebugFunc mocks the Debug method.
	DebugFunc func(msg string, args ...any)

	// ErrorFunc mocks the Error method.
	ErrorFunc func(msg string, args ...any)

	// calls tracks calls to the methods.
	calls struct {
		// Debug holds details about calls to the Debug method.
		Debug []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
		// Error holds details about calls to the Error method.
		Error []struct {
			// Msg is the msg argument value.
			Msg string
			// Args is the args argument value.
			Args []any
		}
	}
	lockDebug sync.RWMutex
	lockError sync.RWMutex
}

// Debug calls DebugFunc.
func (mock *MockLogger) Debug(msg string, args ...any) {
	if mock.DebugFunc == nil {
		panic("MockLogger.DebugFunc: method is nil but Logger.Debug was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockDebug.Lock()
	mock.calls.Debug = append(mock.calls.Debug, callInfo)
	mock.lockDebug.Unlock()
	mock.DebugFunc(msg, args...)
}

// DebugCalls gets all the calls that were made to Debug.
// Check the length with:
//
//	len(mockedLogger.DebugCalls())
func (mock *MockLogger) DebugCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockDebug.RLock()
	calls = mock.calls.Debug
	mock.lockDebug.RUnlock()
	return calls
}

// Error calls ErrorFunc.
func (mock *MockLogger) Error(msg string, args ...any) {
	if mock.ErrorFunc == nil {
		panic("MockLogger.ErrorFunc: method is nil but Logger.Error was just called")
	}
	callInfo := struct {
		Msg  string
		Args []any
	}{
		Msg:  msg,
		Args: args,
	}
	mock.lockError.Lock()
	mock.calls.Error = append(mock.calls.Error, callInfo)
	mock.lockError.Unlock()
	mock.ErrorFunc(msg, args...)
}

// ErrorCalls gets all the calls that were made to Error.
// Check the length with:
//
//	len(mockedLogger.ErrorCalls())
func (mock *MockLogger) ErrorCalls() []struct {
	Msg  string
	Args []any
} {
	var calls []struct {
		Msg  string
		Args []any
	}
	mock.lockError.RLock()
	calls = mock.calls.Error
	mock.lockError.RUnlock()
	return calls
}
