// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mocklockmanager

import (
	"context"
	"sync"

	"github.com/dcbickfo/redcache/internal/lockmanager"
)

// Ensure that MockWaitHandle does implement lockmanager.WaitHandle.
// If this is not the case, regenerate this file with mockery.
var _ lockmanager.WaitHandle = &MockWaitHandle{}

// MockWaitHandle is a mock implementation of lockmanager.WaitHandle.
//
//	func TestSomethingThatUsesWaitHandle(t *testing.T) {
//
//		// make and configure a mocked lockmanager.WaitHandle
//		mockedWaitHandle := &MockWaitHandle{
//			WaitFunc: func(ctx context.Context) error {
//				panic("mock out the Wait method")
//			},
//		}
//
//		// use mockedWaitHandle in code that requires lockmanager.WaitHandle
//		// and then make assertions.
//
//	}
type MockWaitHandle struct {
	// WaitFunc mocks the Wait method.
	WaitFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Wait holds details about calls to the Wait method.
		Wait []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockWait sync.RWMutex
}

// Wait calls WaitFunc.
func (mock *MockWaitHandle) Wait(ctx context.Context) error {
	if mock.WaitFunc == nil {
		panic("MockWaitHandle.WaitFunc: method is nil but WaitHandle.Wait was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	return mock.WaitFunc(ctx)
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedWaitHandle.WaitCalls())
func (mock *MockWaitHandle) WaitCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}
