// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package mockluascript

import (
	"context"
	"sync"

	"github.com/dcbickfo/redcache/internal/luascript"
	"github.com/redis/rueidis"
)

// Ensure that MockExecutor does implement luascript.Executor.
// If this is not the case, regenerate this file with mockery.
var _ luascript.Executor = &MockExecutor{}

// MockExecutor is a mock implementation of luascript.Executor.
//
//	func TestSomethingThatUsesExecutor(t *testing.T) {
//
//		// make and configure a mocked luascript.Executor
//		mockedExecutor := &MockExecutor{
//			ExecFunc: func(ctx context.Context, client rueidis.Client, keys []string, args []string) rueidis.RedisResult {
//				panic("mock out the Exec method")
//			},
//			ExecMultiFunc: func(ctx context.Context, client rueidis.Client, statements ...rueidis.LuaExec) []rueidis.RedisResult {
//				panic("mock out the ExecMulti method")
//			},
//		}
//
//		// use mockedExecutor in code that requires luascript.Executor
//		// and then make assertions.
//
//	}
type MockExecutor struct {
	// ExecFunc mocks the Exec method.
	ExecFunc func(ctx context.Context, client rueidis.Client, keys []string, args []string) rueidis.RedisResult

	// ExecMultiFunc mocks the ExecMulti method.
	ExecMultiFunc func(ctx context.Context, client rueidis.Client, statements ...rueidis.LuaExec) []rueidis.RedisResult

	// calls tracks calls to the methods.
	calls struct {
		// Exec holds details about calls to the Exec method.
		Exec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Client is the client argument value.
			Client rueidis.Client
			// Keys is the keys argument value.
			Keys []string
			// Args is the args argument value.
			Args []string
		}
		// ExecMulti holds details about calls to the ExecMulti method.
		ExecMulti []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Client is the client argument value.
			Client rueidis.Client
			// Statements is the statements argument value.
			Statements []rueidis.LuaExec
		}
	}
	lockExec      sync.RWMutex
	lockExecMulti sync.RWMutex
}

// Exec calls ExecFunc.
func (mock *MockExecutor) Exec(ctx context.Context, client rueidis.Client, keys []string, args []string) rueidis.RedisResult {
	if mock.ExecFunc == nil {
		panic("MockExecutor.ExecFunc: method is nil but Executor.Exec was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Client rueidis.Client
		Keys   []string
		Args   []string
	}{
		Ctx:    ctx,
		Client: client,
		Keys:   keys,
		Args:   args,
	}
	mock.lockExec.Lock()
	mock.calls.Exec = append(mock.calls.Exec, callInfo)
	mock.lockExec.Unlock()
	return mock.ExecFunc(ctx, client, keys, args)
}

// ExecCalls gets all the calls that were made to Exec.
// Check the length with:
//
//	len(mockedExecutor.ExecCalls())
func (mock *MockExecutor) ExecCalls() []struct {
	Ctx    context.Context
	Client rueidis.Client
	Keys   []string
	Args   []string
} {
	var calls []struct {
		Ctx    context.Context
		Client rueidis.Client
		Keys   []string
		Args   []string
	}
	mock.lockExec.RLock()
	calls = mock.calls.Exec
	mock.lockExec.RUnlock()
	return calls
}

// ExecMulti calls ExecMultiFunc.
func (mock *MockExecutor) ExecMulti(ctx context.Context, client rueidis.Client, statements ...rueidis.LuaExec) []rueidis.RedisResult {
	if mock.ExecMultiFunc == nil {
		panic("MockExecutor.ExecMultiFunc: method is nil but Executor.ExecMulti was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Client     rueidis.Client
		Statements []rueidis.LuaExec
	}{
		Ctx:        ctx,
		Client:     client,
		Statements: statements,
	}
	mock.lockExecMulti.Lock()
	mock.calls.ExecMulti = append(mock.calls.ExecMulti, callInfo)
	mock.lockExecMulti.Unlock()
	return mock.ExecMultiFunc(ctx, client, statements...)
}

// ExecMultiCalls gets all the calls that were made to ExecMulti.
// Check the length with:
//
//	len(mockedExecutor.ExecMultiCalls())
func (mock *MockExecutor) ExecMultiCalls() []struct {
	Ctx        context.Context
	Client     rueidis.Client
	Statements []rueidis.LuaExec
} {
	var calls []struct {
		Ctx        context.Context
		Client     rueidis.Client
		Statements []rueidis.LuaExec
	}
	mock.lockExecMulti.RLock()
	calls = mock.calls.ExecMulti
	mock.lockExecMulti.RUnlock()
	return calls
}
